module.exports = {
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  INVALID_ARGUMENT: 'INVALID_ARGUMENT',
  USERNAME_ALREADY_EXISTS: 'USERNAME_ALREADY_EXISTS',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
};
