apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service ## a new Service object named "nodejs-app"
spec:
  selector:
    app: nodejs-app
  type: LoadBalancer
  ports: ## targets TCP port 8080 on any Pod with the app=nodejs-app label
  - protocol: TCP
    port: 8080
    targetPort: 8080
