apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-deployment
  labels:
    app: nodejs-app
spec:
  selector:
     matchLabels:
       app: nodejs-app
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - image: oscarjunior/nodejs-app:note-service
          imagePullPolicy: Always
          name: nodejs-app-container
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "PORT"
            - name: JWT_PRIVATE_KEY
              value: "JWT_PRIVATE_KEY"
            - name: NODE_ENV
              value: "NODE_ENV"
            - name: MONGO_URI
              value: "MONGO_URI"
            - name: MONGO_DB_NAME
              value: "MONGO_DB_NAME"
            - name: NOTES_END_POINT
              value: "NOTES_END_POINT"
