version: '3'

services:
  mongodb:
    image: mongo:3.6.13-xenial
    command: --smallfiles
    volumes:
      - mongodbvolume:/data/db
    ports:
      - '27017:27017'
    networks:
      - backend

  boilerplate-nodejs-basic-architecture:
    build:
      context: '.'
    command: 'npm start'
    restart: always
    depends_on:
      - mongodb
    ports:
      - '8080:8080'
      - '9229:9229'
    volumes:
      - '.:/app'
    networks:
      - backend
    links:
      - mongodb

networks:
  backend:
    driver: bridge

volumes:
  mongodbvolume:
