version: '3'

services:
  mongodb:
    image: mongo:3.6.13-xenial
    command: --smallfiles
    volumes:
      - mongodbvolume:/data/db
    ports:
      - '27019:27017'
    networks:
      - backend

  nodejs-app-structure:
    env_file: .envrc.sample
    build:
      context: '.'
    restart: always
    depends_on:
      - mongodb
    volumes:
      - '.:/app'
      - '/app/node_modules'
      - '/app/logs'
    networks:
      - backend
    links:
      - mongodb

networks:
  backend:
    driver: bridge

volumes:
  mongodbvolume:
